---
namespace: "vfricou"
name: "apps"

version: "1.0.0"

readme: "README.md"
authors:
  - "Vincent FRICOU"
description: "Various applications collection containing roles and modules"

license:
  - "AGPL-3.0-only"
license_file: 'LICENSE'

repository: "https://github.com/vfricou/vfricou.apps/"
documentation: "https://vfricou.github.io/collection-documentation/"
homepage: "https://github.com/vfricou/vfricou.apps/"
issues: "https://github.com/vfricou/vfricou.apps/issues"
build_ignore: []

tags: []

dependencies:
  community.crypto: '>=2.26.1'
