---
- name: 'Restart nginx'
  become: true
  tags:
    - nginx
    - nginx_configure
    - nginx_general
    - nginx_config_files
    - nginx_static_configs
    - nginx_vhost
  ansible.builtin.systemd_service:
    name: 'nginx'
    enabled: true
    state: restarted
    daemon_reload: true
