---
- name: 'Restart minio'
  become: true
  tags:
    - minio
    - minio_install
    - minio_configure
  ansible.builtin.systemd_service:
    name: 'minio'
    state: restarted
    daemon_reload: true
    enabled: true
